version: '3.8'

services:
	node:
		image: mastermind:latest
		ports:
			- 3005:3005
			environment:
				DATABASE_URL: mongo:27017

mongo:
	image: mongo
	restart: always
	ports:
		- 27017
		environment:
			MONGO_INITDB_ROOT_USERNAME: root
			MONGO_INITDB_ROOT_PASSWORD: cats

mongo-express:
	image: mongo-express
	restart: always
	ports:
		- 8081:8081
		environment:
			ME_CONFIG_MONGODB_ADMINUSERNAME: root
			ME_CONFIG_MONGODB_ADMINPASSWORD: cats