apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastermind-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: mastermind
        image: coffeesnakes/mastermind:latest
        resources:
        ports:
          - containerPort: 3000
        env:
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
        - name: DATABASE_URL
          value: mongo-service